id: I554BB464
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:32:07+00:00'
last_modified: '2022-06-08T13:20:59.035071+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21757
  title: རྟའི་ཚེ་ཡི་རིག་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    388E:
      image_group_id: I1KG21857
      title: Volume 1 of rta'i tshe yi rig byed/
      total_pages: 290
      order: 1
      base_file: 388E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
