id: opecha:P007027
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21757
  title: རྟའི་ཚེ་ཡི་རིག་བྱེད།
  volume:
    2e97ebee1f1a40c09321d4591174d97a:
      image_group_id: I1KG21857
      title: Volume 1 of rta'i tshe yi rig byed/
      volume_number: 1
      total_pages: 290
  author: ''
ebook_metadata:
  title: རྟའི་ཚེ་ཡི་རིག་བྱེད།
  author: ''
  sku: P007027
  cover: cover.jpg
  layers:
  - pagination
