id: P007027
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21757
  title: རྟའི་ཚེ་ཡི་རིག་བྱེད།
  author: ''
  volumes:
    ec657767d0e644a1a3e2327865cc011e:
      image_group_id: I1KG21857
      title: ''
      volume_number: 1
      total_pages: 290
ebook_metadata:
  title: རྟའི་ཚེ་ཡི་རིག་བྱེད།
  author: ''
  sku: P007027
  cover: cover.jpg
  layers:
  - pagination
